version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: w1
    volumes:
      - ./web/html:/usr/share/nginx/html
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

